### ISSUE TITLE
Unable to claim rewards when using imToken

### ISSUE THREAD

**Issue by zozyo** [Phala-Network/apps#114]
Now imToken can connect to app and see account info after fixed #108 

However, imToken failed to found wallet when trying to claim stake rewards.

![20220413011434](https://user-images.githubusercontent.com/5868939/163017701-d9125e08-e8d1-4a50-b584-420769284ee8.png)

**Comment by kingsleydon** [comment]
This is a known issue about imToken, they do not support parachains yet. Unfortunately we are not particularly clear about their development plans.

**Comment by h4x3rotab** [comment]
We have the impression imtoken was never usable. In the forum post the demo was done with TP wallet. We can run a legacy phala app and have a try of imtoken
