### ISSUE TITLE
Emoji symbol should not be parsed for pool owner

### ISSUE THREAD

**Issue by zozyo** [Phala-Network/apps#140]
![image](https://user-images.githubusercontent.com/5868939/166859006-e7c7da2d-0daa-4106-8a94-719b8fe9f10a.png)

https://khala.subscan.io/account/3zzvndqUgtBBNitv2nCFokFvGZdJnjQvPw55bgYVpjYrBGns

Found someone using emoji in their id, pretending to be verified but actually not. It's a kind of fraud. Emoji symbol should not be parsed for pool owner.

**Comment by zozyo** [comment]
![image](https://user-images.githubusercontent.com/5868939/167120955-d9cfd812-9b18-4ae6-8c28-ae00337640d3.png)
![image](https://user-images.githubusercontent.com/5868939/167120969-6dd53fdc-6eea-4a04-9523-8dac5ab4e190.png)

**Comment by kingsleydon** [comment]
Got it, but filter all emoji can be confusing too as it won't match what's shown on other sites like subscan.

Might think of a better way to handle the display of identity later.

**Comment by kingsleydon** [comment]
<img width="201" alt="image" src="https://user-images.githubusercontent.com/10992364/169093525-e997e5cd-7da3-45ba-8a96-0e2349b4e3b0.png">

The unknown icon is added in #150
