### ISSUE TITLE
TypeError: Failed to fetch error when I enter mining page

### ISSUE THREAD

**Issue by merryjane-btc** [Phala-Network/apps#159]
TypeError is occurred when I entered page https://app.phala.network/mining/ and saw the console log.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/100121847/169491756-ed346c46-62fa-4fb2-b117-1524a0c39d12.png">

**Comment by kingsleydon** [comment]
This error is thrown by the zendesk sdk and does not affect the app.
