### ISSUE TITLE
Not able to connect Polkadot.js extension in Brave/Chrome/Firefox Browser

### ISSUE THREAD

**Issue by michaelmowry** [Phala-Network/apps#19]
I am unable to connect the polkadot.js browser extension to the Phala Web App.  This worked until late last week and has failed since then.  I have tried the following:
- Multiple browsers, fresh installs of the browser and extension
- Clearing the cache
- Ensuring popup blockers are disabled
- Ensuring my Khala account is set to "Allow use on any chain" in Polkadot.js
- Ensuring that the polkadot.js has access to the https://app.phala.network/ site
- Ensuring that my metadata extensions are updated in https://polkadot.js.org/apps/#/settings/metadata

OS: Windows
Polkadot.js Extension Version: 0.41.2 on Chrome, 0.41.1 on Brave

I have also noticed a similar problem with the Karura app.  I posted this issue [here](https://github.com/polkadot-js/extension/issues/835) as well, but per the response they say that this is an application development issue on the Khala side.

![2021-09-22_14-04-40](https://user-images.githubusercontent.com/7070665/134424534-5319b0eb-ba4c-47a8-9fc5-eef507e0d602.png)

**Comment by limichange** [comment]
Thank you for submitting your question, we will try to reproduce the issue and resolve it. Thank you so much.

**Comment by michaelmowry** [comment]
@limichange I was able to resolve this by importing my accounts to a new install of the polkadot.js extension by seed.  For me, importing them by json was causing the issue above.  I posted about it here - https://github.com/polkadot-js/extension/issues/835.  You can close this, thank you!
