### ISSUE TITLE
Should disallow to "approve" without the target address & amount in bridge

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/apps#39]
Currently, even without entering the address and the amount, we can still click "Approve" button in the bridge page:

![image](https://user-images.githubusercontent.com/1343470/143304109-90756672-f8b1-4241-a298-3a9a6f60f345.png)

It's ok in the common sense but still not optimal for the noob users. We have heard reports saying they didn't understand how the bridge works and what they need to do, but still wasted the gas fee.

Suggestion: make "Approve" button disabled if the input address or the amount is empty or invalid.

**Comment by kingsleydon** [comment]
Legacy bridge page has accomplished its mission 🥲
